### PR TITLE
Add downloadable CSV files

### LINKED ISSUE #296: Add timeseries of data at 107 cities around the globe in CSV format to the datasets.md
I currently have a bunch of CSVs for 107 cities in an S3 bucket. I'm opening this issue as a reminder to myself ;). 

- [ ] Add CSVs to datasets.md
- [ ] Ensure metadata are tacked to the top of each of those CSVs

### PR DESCRIPTION
**Pull request by andersy005**
- Fixes #296

### CODE REVIEW

**Comment by andersy005** [comment]
pre-commit.ci autofix

**Comment by andersy005** [comment]
pre-commit.ci autofix

**Comment by andersy005** [comment]
pre-commit.ci autofix

**Review by norlandrhagen — APPROVED** [review]

**Comment by andersy005** [comment]
Cc @orianac, @freeman-lab, let me know whether you have any feedback and/or there's anything missing from this.

**Pull request merged**
